info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T17:02:27.753Z"}
info: Connected to the database. {"timestamp":"2022-07-28T17:02:27.841Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T17:04:37.122Z"}
info: Connected to the database. {"timestamp":"2022-07-28T17:04:37.172Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T17:15:46.114Z"}
info: Connected to the database. {"timestamp":"2022-07-28T17:15:46.167Z"}
error: 
    status - 500 
    message - TypeError: UserService.userRegistration is not a function
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\controllers\/user.controller.js:12:37)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12
    at userRegistration (H:\NodeJS\fundooNotes\fundooNotes\src\controllers\/user.controller.js:10:31)
    at Layer.handle [as handle_request] (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\route.js:144:13)
    at newUserValidator (H:\NodeJS\fundooNotes\fundooNotes\src\validators\/user.validator.js:19:5)
    at Layer.handle [as handle_request] (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\route.js:114:3) 
    url - /api/v1/users/userRegistration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-28T17:15:58.476Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T17:16:55.251Z"}
info: Connected to the database. {"timestamp":"2022-07-28T17:16:55.320Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:00:03.320Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:00:03.378Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: Fundoo_Notes.users index: email_1 dup key: { email: " rohitshinde@gmail.com " } 
      url - /api/v1/users/userRegistration 
      method - POST 
      IP - ::1
     {"timestamp":"2022-07-28T18:00:20.482Z"}
error: 
    status - 500 
    message - RangeError: Invalid status code: 11000
    at new NodeError (node:internal/errors:371:5)
    at ServerResponse.writeHead (node:_http_server:274:11)
    at ServerResponse.writeHead (H:\NodeJS\fundooNotes\fundooNotes\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (node:_http_server:265:8)
    at write_ (node:_http_outgoing:766:9)
    at ServerResponse.end (node:_http_outgoing:855:5)
    at ServerResponse.send (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\response.js:232:10)
    at ServerResponse.json (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\response.js:278:15)
    at appErrorHandler (H:\NodeJS\fundooNotes\fundooNotes\src\middlewares\/error.middleware.js:36:26)
    at Layer.handle_error (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:326:13)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:346:12)
    at Immediate.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Immediate._onImmediate (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:646:15)
    at processImmediate (node:internal/timers:468:21) 
    url - /api/v1/users/userRegistration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-28T18:00:20.522Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:11:45.742Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:11:45.808Z"}
error: 
    status - 500 
    message - Error: User already exist
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:9:9)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/userRegistration 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-28T18:11:58.484Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:19:06.948Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:19:07.008Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:22:18.677Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:22:18.736Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:25:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-28T18:22:47.733Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:56:11.045Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:56:11.127Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-28T18:58:11.870Z"}
info: Connected to the database. {"timestamp":"2022-07-28T18:58:11.927Z"}
error: 
    status - 500 
    message - Error: password not match
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:33:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-28T19:00:37.108Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-29T12:27:09.668Z"}
info: Connected to the database. {"timestamp":"2022-07-29T12:27:09.801Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-29T12:28:31.176Z"}
info: Connected to the database. {"timestamp":"2022-07-29T12:28:31.229Z"}
error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Fri Jul 29 2022 18:01:51 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1201558},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18286953,"external":19936700,"heapTotal":48238592,"heapUsed":43401696,"rss":80117760},"pid":13564,"uid":null,"version":"v16.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","timestamp":"2022-07-29T12:31:51.429Z","trace":[]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-29T12:32:58.268Z"}
info: Connected to the database. {"timestamp":"2022-07-29T12:32:58.339Z"}
error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Fri Jul 29 2022 18:03:24 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1201651},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18374324,"external":19927922,"heapTotal":48762880,"heapUsed":43676824,"rss":81293312},"pid":14312,"uid":null,"version":"v16.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","timestamp":"2022-07-29T12:33:24.956Z","trace":[]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-29T12:33:32.802Z"}
info: Connected to the database. {"timestamp":"2022-07-29T12:33:32.870Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-29T12:34:22.305Z"}
info: Connected to the database. {"timestamp":"2022-07-29T12:34:22.359Z"}
error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Fri Jul 29 2022 18:04:42 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1201729},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19354133,"external":22715108,"heapTotal":82386944,"heapUsed":54315392,"rss":115658752},"pid":16980,"uid":null,"version":"v16.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","timestamp":"2022-07-29T12:34:42.485Z","trace":[]}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T12:35:42.747Z"}
info: Connected to the database. {"timestamp":"2022-07-29T12:35:42.816Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T12:43:27.749Z"}
info: Connected to the database. {"timestamp":"2022-07-29T12:43:27.817Z"}
error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Fri Jul 29 2022 18:16:12 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1202419},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18293195,"external":19938449,"heapTotal":47976448,"heapUsed":44142280,"rss":80699392},"pid":13564,"uid":null,"version":"v16.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","timestamp":"2022-07-29T12:46:12.789Z","trace":[]}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T12:48:12.342Z"}
info: Connected to the database. {"timestamp":"2022-07-29T12:48:12.444Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T12:50:43.709Z"}
info: Connected to the database. {"timestamp":"2022-07-29T12:50:43.776Z"}
error: 
    status - 500 
    message - ReferenceError: HttpStatus is not defined
    at noteValidator (H:\NodeJS\fundooNotes\fundooNotes\src\validators\/note.validator.js:11:16)
    at Layer.handle [as handle_request] (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\route.js:144:13)
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\middlewares\/auth.middleware.js:25:5)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/addNote 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T12:50:51.955Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T12:54:05.392Z"}
info: Connected to the database. {"timestamp":"2022-07-29T12:54:05.459Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:23:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T12:56:03.689Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:23:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T12:58:25.465Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:23:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T12:59:08.316Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:23:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T12:59:47.074Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T13:00:16.914Z"}
info: Connected to the database. {"timestamp":"2022-07-29T13:00:16.982Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:23:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T13:00:40.652Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T13:02:42.173Z"}
info: Connected to the database. {"timestamp":"2022-07-29T13:02:42.247Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:23:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T13:02:53.582Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T13:04:49.212Z"}
info: Connected to the database. {"timestamp":"2022-07-29T13:04:49.268Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:23:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T13:04:56.556Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T13:18:46.262Z"}
info: Connected to the database. {"timestamp":"2022-07-29T13:18:46.325Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T13:27:42.305Z"}
info: Connected to the database. {"timestamp":"2022-07-29T13:27:42.362Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T13:29:22.145Z"}
info: Connected to the database. {"timestamp":"2022-07-29T13:29:22.214Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:22:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T13:31:10.662Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T13:39:15.910Z"}
info: Connected to the database. {"timestamp":"2022-07-29T13:39:15.968Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:22:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T13:39:35.620Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:22:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T13:40:00.507Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T16:45:13.202Z"}
info: Connected to the database. {"timestamp":"2022-07-29T16:45:13.264Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T16:51:55.458Z"}
info: Connected to the database. {"timestamp":"2022-07-29T16:51:55.520Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:22:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T16:52:26.962Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:01:37.484Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:01:37.549Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:22:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T17:02:03.037Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:15:00.928Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:15:00.989Z"}
error: 
    status - 500 
    message - Error: User not exist
    at _callee2$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/user.service.js:22:11)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T17:15:25.537Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:16:14.039Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:16:14.093Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:20:24.253Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:20:24.312Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:21:03.343Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:21:03.396Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:26:06.745Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:26:06.802Z"}
error: 
    status - 500 
    message - ValidationError: "Title" is required 
    url - /api/v1/note/addNote 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T17:26:17.568Z"}
error: uncaughtException: data is not defined
ReferenceError: data is not defined
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\middlewares\/auth.middleware.js:29:13)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Fri Jul 29 2022 22:57:26 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1219293},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18296402,"external":19850000,"heapTotal":48762880,"heapUsed":44233592,"rss":81080320},"pid":18248,"uid":null,"version":"v16.14.2"},"stack":"ReferenceError: data is not defined\n    at _callee$ (H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js:29:13)\n    at tryCatch (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-07-29T17:27:26.310Z","trace":[{"column":13,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js","function":"_callee$","line":29,"method":null,"native":false},{"column":17,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":117,"method":"next","native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:32:29.250Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:32:29.309Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:34:30.842Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:34:30.898Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parse (H:\NodeJS\fundooNotes\fundooNotes\node_modules\body-parser\lib\types\json.js:89:19)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:201:9)
    at invokeCallback (H:\NodeJS\fundooNotes\fundooNotes\node_modules\raw-body\index.js:231:16)
    at done (H:\NodeJS\fundooNotes\fundooNotes\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (H:\NodeJS\fundooNotes\fundooNotes\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:538:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/note/addNote 
    method - POST 
    IP - ::1
   {"timestamp":"2022-07-29T17:35:46.779Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:40:55.384Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:40:55.439Z"}
error: uncaughtException: data is not defined
ReferenceError: data is not defined
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\middlewares\/auth.middleware.js:29:12)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Fri Jul 29 2022 23:11:57 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1220164},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18296405,"external":19850003,"heapTotal":49025024,"heapUsed":44239984,"rss":81162240},"pid":13084,"uid":null,"version":"v16.14.2"},"stack":"ReferenceError: data is not defined\n    at _callee$ (H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js:29:12)\n    at tryCatch (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-07-29T17:41:57.799Z","trace":[{"column":12,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js","function":"_callee$","line":29,"method":null,"native":false},{"column":17,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":117,"method":"next","native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:45:23.532Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:45:23.587Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:48:28.615Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:48:28.678Z"}
error: uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>". {"date":"Fri Jul 29 2022 23:20:17 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1220664},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18284366,"external":19837964,"heapTotal":49287168,"heapUsed":44081424,"rss":82022400},"pid":15612,"uid":null,"version":"v16.14.2"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"#<Object>\".","timestamp":"2022-07-29T17:50:18.007Z","trace":[]}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:51:55.715Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:51:55.784Z"}
error: uncaughtException: data is not defined
ReferenceError: data is not defined
    at _callee$ (H:\NodeJS\fundooNotes\fundooNotes\src\middlewares\/auth.middleware.js:29:13)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Fri Jul 29 2022 23:26:26 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1221033},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":18286946,"external":19957369,"heapTotal":49025024,"heapUsed":44596016,"rss":80556032},"pid":13792,"uid":null,"version":"v16.14.2"},"stack":"ReferenceError: data is not defined\n    at _callee$ (H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js:29:13)\n    at tryCatch (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-07-29T17:56:26.459Z","trace":[{"column":13,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\middlewares\\/auth.middleware.js","function":"_callee$","line":29,"method":null,"native":false},{"column":17,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.next","line":117,"method":"next","native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_next","line":25,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T17:56:34.267Z"}
info: Connected to the database. {"timestamp":"2022-07-29T17:56:34.322Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T18:11:58.206Z"}
info: Connected to the database. {"timestamp":"2022-07-29T18:11:58.315Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T18:17:36.754Z"}
info: Connected to the database. {"timestamp":"2022-07-29T18:17:36.808Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T18:20:10.069Z"}
info: Connected to the database. {"timestamp":"2022-07-29T18:20:10.121Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T18:29:33.133Z"}
info: Connected to the database. {"timestamp":"2022-07-29T18:29:33.197Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-07-29T18:39:34.271Z"}
info: Connected to the database. {"timestamp":"2022-07-29T18:39:34.333Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T09:00:13.173Z"}
info: Connected to the database. {"timestamp":"2022-07-30T09:00:13.236Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T10:16:53.006Z"}
info: Connected to the database. {"timestamp":"2022-07-30T10:16:53.059Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T10:52:51.549Z"}
info: Connected to the database. {"timestamp":"2022-07-30T10:52:51.599Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T10:56:29.770Z"}
info: Connected to the database. {"timestamp":"2022-07-30T10:56:29.825Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T11:00:14.543Z"}
info: Connected to the database. {"timestamp":"2022-07-30T11:00:14.624Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T11:03:09.950Z"}
info: Connected to the database. {"timestamp":"2022-07-30T11:03:10.010Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T11:13:42.687Z"}
info: Connected to the database. {"timestamp":"2022-07-30T11:13:42.751Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T15:10:44.720Z"}
info: Connected to the database. {"timestamp":"2022-07-30T15:10:44.828Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T15:24:56.633Z"}
info: Connected to the database. {"timestamp":"2022-07-30T15:24:56.789Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T15:29:46.204Z"}
info: Connected to the database. {"timestamp":"2022-07-30T15:29:46.335Z"}
error: uncaughtException: $ is not defined
ReferenceError: $ is not defined
    at _callee3$ (H:\NodeJS\fundooNotes\fundooNotes\src\controllers\/note.controller.js:49:17)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.throw (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _throw (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:29:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {"date":"Sat Jul 30 2022 21:00:17 GMT+0530 (India Standard Time)","error":{},"exception":true,"os":{"loadavg":[0,0,0],"uptime":1298664},"process":{"argv":["node","H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\index.js"],"cwd":"H:\\NodeJS\\fundooNotes\\fundooNotes","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":19552647,"external":22770079,"heapTotal":82661376,"heapUsed":59317544,"rss":116396032},"pid":12836,"uid":null,"version":"v16.14.2"},"stack":"ReferenceError: $ is not defined\n    at _callee3$ (H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\controllers\\/note.controller.js:49:17)\n    at tryCatch (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.throw (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _throw (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:29:9)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","timestamp":"2022-07-30T15:30:17.431Z","trace":[{"column":17,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\controllers\\/note.controller.js","function":"_callee3$","line":49,"method":null,"native":false},{"column":17,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"tryCatch","line":86,"method":null,"native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator._invoke","line":66,"method":"_invoke","native":false},{"column":21,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js","function":"Generator.throw","line":117,"method":"throw","native":false},{"column":24,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"asyncGeneratorStep","line":3,"method":null,"native":false},{"column":9,"file":"H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js","function":"_throw","line":29,"method":null,"native":false},{"column":5,"file":"node:internal/process/task_queues","function":"processTicksAndRejections","line":96,"method":null,"native":false}]}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-30T15:32:56.823Z"}
info: Connected to the database. {"timestamp":"2022-07-30T15:32:56.976Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T07:35:28.444Z"}
info: Connected to the database. {"timestamp":"2022-07-31T07:35:28.592Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T07:36:51.796Z"}
info: Connected to the database. {"timestamp":"2022-07-31T07:36:51.897Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T07:39:28.943Z"}
info: Connected to the database. {"timestamp":"2022-07-31T07:39:29.071Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T07:44:23.169Z"}
info: Connected to the database. {"timestamp":"2022-07-31T07:44:23.268Z"}
error: 
    status - 500 
    message - CastError: Cast to string failed for value "{ UserID: ' prachishinde@gmail.com ' }" (type Object) at path "UserID" for model "Note"
    at model.Query.exec (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\query.js:4498:21)
    at model.Query.Query.then (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\query.js:4592:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/note/getAllNote 
    method - GET 
    IP - ::1
   {"timestamp":"2022-07-31T07:44:50.683Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T07:50:15.802Z"}
info: Connected to the database. {"timestamp":"2022-07-31T07:50:15.878Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T07:56:50.107Z"}
info: Connected to the database. {"timestamp":"2022-07-31T07:56:50.181Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T07:58:08.218Z"}
info: Connected to the database. {"timestamp":"2022-07-31T07:58:08.298Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T08:07:50.191Z"}
info: Connected to the database. {"timestamp":"2022-07-31T08:07:50.296Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T08:11:51.777Z"}
info: Connected to the database. {"timestamp":"2022-07-31T08:11:51.867Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T08:48:38.200Z"}
info: Connected to the database. {"timestamp":"2022-07-31T08:48:38.334Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-07-31T08:58:37.897Z"}
info: Connected to the database. {"timestamp":"2022-07-31T08:58:38.080Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T02:41:16.458Z"}
info: Connected to the database. {"timestamp":"2022-08-01T02:41:16.540Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T02:44:42.230Z"}
info: Connected to the database. {"timestamp":"2022-08-01T02:44:42.314Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T02:48:05.695Z"}
info: Connected to the database. {"timestamp":"2022-08-01T02:48:05.769Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T02:50:10.587Z"}
info: Connected to the database. {"timestamp":"2022-08-01T02:50:10.670Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T03:09:35.167Z"}
info: Connected to the database. {"timestamp":"2022-08-01T03:09:35.222Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T03:26:33.572Z"}
info: Connected to the database. {"timestamp":"2022-08-01T03:26:33.634Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T03:27:58.941Z"}
info: Connected to the database. {"timestamp":"2022-08-01T03:27:58.996Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T03:35:48.838Z"}
info: Connected to the database. {"timestamp":"2022-08-01T03:35:48.893Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T03:45:41.722Z"}
info: Connected to the database. {"timestamp":"2022-08-01T03:45:41.790Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T03:49:06.691Z"}
info: Connected to the database. {"timestamp":"2022-08-01T03:49:06.743Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T03:51:50.845Z"}
info: Connected to the database. {"timestamp":"2022-08-01T03:51:50.896Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T03:54:50.756Z"}
info: Connected to the database. {"timestamp":"2022-08-01T03:54:50.817Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T03:56:19.718Z"}
info: Connected to the database. {"timestamp":"2022-08-01T03:56:19.787Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T03:56:56.294Z"}
info: Connected to the database. {"timestamp":"2022-08-01T03:56:56.361Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T04:01:29.365Z"}
info: Connected to the database. {"timestamp":"2022-08-01T04:01:29.419Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T04:02:16.462Z"}
info: Connected to the database. {"timestamp":"2022-08-01T04:02:16.519Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T04:03:50.878Z"}
info: Connected to the database. {"timestamp":"2022-08-01T04:03:50.931Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T04:14:34.761Z"}
info: Connected to the database. {"timestamp":"2022-08-01T04:14:34.814Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T04:26:20.949Z"}
info: Connected to the database. {"timestamp":"2022-08-01T04:26:21.015Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T04:28:26.345Z"}
info: Connected to the database. {"timestamp":"2022-08-01T04:28:26.415Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T04:31:38.033Z"}
info: Connected to the database. {"timestamp":"2022-08-01T04:31:38.088Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T17:33:33.918Z"}
error: Could not connect to the database. connect ECONNREFUSED 127.0.0.1:27017 {"reason":{"commonWireVersion":null,"compatibilityError":null,"compatible":true,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"logicalSessionTimeoutMinutes":null,"maxElectionId":null,"maxSetVersion":null,"servers":{},"setName":null,"stale":false,"type":"Single"},"stack":"MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at NativeConnection.Connection.openUri (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\mongoose\\lib\\connection.js:847:32)\n    at H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\mongoose\\lib\\index.js:351:10\n    at H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:32:5\n    at new Promise (<anonymous>)\n    at promiseOrCallback (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\mongoose\\lib\\helpers\\promiseOrCallback.js:31:10)\n    at Mongoose._promiseOrCallback (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\mongoose\\lib\\index.js:1149:10)\n    at Mongoose.connect (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\mongoose\\lib\\index.js:350:20)\n    at _callee$ (H:\\NodeJS\\fundooNotes\\fundooNotes\\src\\config\\/database.js:12:20)\n    at tryCatch (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:86:17)\n    at Generator._invoke (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:66:24)\n    at Generator.next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\regeneratorRuntime.js:117:21)\n    at asyncGeneratorStep (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:3:24)\n    at _next (H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:25:9)\n    at H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:32:7\n    at new Promise (<anonymous>)\n    at H:\\NodeJS\\fundooNotes\\fundooNotes\\node_modules\\@babel\\runtime\\helpers\\asyncToGenerator.js:21:12","timestamp":"2022-08-01T17:34:03.883Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T17:36:57.152Z"}
info: Connected to the database. {"timestamp":"2022-08-01T17:36:57.273Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T18:19:10.631Z"}
info: Connected to the database. {"timestamp":"2022-08-01T18:19:10.692Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T18:30:31.982Z"}
info: Connected to the database. {"timestamp":"2022-08-01T18:30:32.035Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findByIdAndUpdate (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\model.js:2694:19)
    at _callee6$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/note.service.js:38:29)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (H:\NodeJS\fundooNotes\fundooNotes\src\services\/note.service.js:37:26)
    at _callee6$ (H:\NodeJS\fundooNotes\fundooNotes\src\controllers\/note.controller.js:86:40)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/note/62e81be837100015b8f83936/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-08-01T18:32:16.715Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findByIdAndUpdate (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\model.js:2694:19)
    at _callee6$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/note.service.js:38:29)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.archiveNotes (H:\NodeJS\fundooNotes\fundooNotes\src\services\/note.service.js:37:26)
    at _callee6$ (H:\NodeJS\fundooNotes\fundooNotes\src\controllers\/note.controller.js:86:40)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/note/62e81be837100015b8f83936/isArchive 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-08-01T18:38:54.064Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T18:51:05.395Z"}
info: Connected to the database. {"timestamp":"2022-08-01T18:51:05.538Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findByIdAndUpdate (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\model.js:2694:19)
    at _callee7$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/note.service.js:54:29)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.isTrash (H:\NodeJS\fundooNotes\fundooNotes\src\services\/note.service.js:53:23)
    at _callee7$ (H:\NodeJS\fundooNotes\fundooNotes\src\controllers\/note.controller.js:99:40)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/note/62e81be837100015b8f83936/isDelete 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-08-01T18:55:19.146Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T18:57:07.858Z"}
info: Connected to the database. {"timestamp":"2022-08-01T18:57:07.918Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-01T19:01:27.952Z"}
info: Connected to the database. {"timestamp":"2022-08-01T19:01:28.019Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findOneAndDelete (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\model.js:2792:19)
    at _callee7$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/note.service.js:54:29)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.isTrash (H:\NodeJS\fundooNotes\fundooNotes\src\services\/note.service.js:53:23)
    at _callee7$ (H:\NodeJS\fundooNotes\fundooNotes\src\controllers\/note.controller.js:99:40)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/note/62e81be837100015b8f83936/isDelete 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-08-01T19:01:33.160Z"}
error: 
    status - 500 
    message - MongooseError: Callback must be a function, got [object Object]
    at Function.Model.$handleCallbackError (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\model.js:5067:11)
    at Function.findOneAndDelete (H:\NodeJS\fundooNotes\fundooNotes\node_modules\mongoose\lib\model.js:2792:19)
    at _callee7$ (H:\NodeJS\fundooNotes\fundooNotes\src\services\/note.service.js:54:29)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at Object.isTrash (H:\NodeJS\fundooNotes\fundooNotes\src\services\/note.service.js:53:23)
    at _callee7$ (H:\NodeJS\fundooNotes\fundooNotes\src\controllers\/note.controller.js:99:40)
    at tryCatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21) 
    url - /api/v1/note/62e81be837100015b8f83936/isDelete 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-08-01T19:01:49.864Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-02T02:38:47.653Z"}
info: Connected to the database. {"timestamp":"2022-08-02T02:38:47.718Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-02T02:42:02.324Z"}
info: Connected to the database. {"timestamp":"2022-08-02T02:42:02.404Z"}
error: 
    status - 500 
    message - Error: The boolean type does not allow arguments
    at new module.exports (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@hapi\hoek\lib\error.js:23:19)
    at module.exports (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@hapi\hoek\lib\assert.js:21:11)
    at Object.root.<computed> (H:\NodeJS\fundooNotes\fundooNotes\node_modules\@hapi\joi\lib\index.js:57:13)
    at noteValidator (H:\NodeJS\fundooNotes\fundooNotes\src\validators\/note.validator.js:7:20)
    at Layer.handle [as handle_request] (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:346:12)
    at next (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:175:3)
    at router (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:328:13)
    at H:\NodeJS\fundooNotes\fundooNotes\node_modules\express\lib\router\index.js:286:9 
    url - /api/v1/note/addNote 
    method - POST 
    IP - ::1
   {"timestamp":"2022-08-02T02:42:30.085Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-02T02:43:28.358Z"}
info: Connected to the database. {"timestamp":"2022-08-02T02:43:28.429Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-08-02T02:47:08.670Z"}
info: Connected to the database. {"timestamp":"2022-08-02T02:47:08.726Z"}
